version: "3.7"
services:

  book_db:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    environment:
      POSTGRES_USER: "bookuser"
      POSTGRES_PASSWORD: "bookdbpass"
      POSTGRES_DB: "books_db"

  redis_books_db:
    image: redis
    command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"

  local-rabbit-books:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-books
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
      restart: always
    volumes:
      - rabbitmq-data-books:/var/lib/rabbitmq

volumes:
  database-data: # named volumes can be managed easier using docker-compose
  rabbitmq-data-books: