version: 2.1
description:

orbs:
  gradle: circleci/gradle@2

executors:
  gradle:
    docker:
      - image: circleci/openjdk:11-jdk
  postgres:
    docker:
      - image: circleci/openjdk:11-jdk
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: bookuser
          POSTGRES_PASSWORD: bookdbpass
          POSTGRES_DB: books_db

jobs:
  build:
    parameters:
      executor:
        description: The name of custom executor to use
        type: executor
        default: gradle
      artifacts_path:
        description: Path to artifacts
        type: string
        default: '**/build/libs/*.jar'
    executor: postgres
    steps:
      - checkout

      - gradle/with_cache:
          steps:
            - run:
                name: Test
                command: ./gradlew test